name: block-sparse-attn-ck
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/rocm6.0
    - torch==2.3
    - transformers
    # - scikit-build==0.17.6
    - scikit-build
